packages:
  - .
  - vendor/superdoc-document-api
  - vendor/univer/common/*
  - vendor/univer/mockdata
  - vendor/univer/presets
  - vendor/univer/presets/packages/*
  - vendor/univer/packages/*

allowBuilds:
  '@swc/core': false
  esbuild: true
  protobufjs: true

overrides:
  react: 18.3.1
  react-dom: 18.3.1
